/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'brent.gardner' at '1/13/17 10:11 AM' with Gradle 3.1
 *
 * @author brent.gardner, @date 1/13/17 10:11 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
